version: '3.9'

services:
  server:
    build: ./app
    ports:
      - '8000:8000'
    environment:
      - PG_PASSWORD=123456
      - PG_HOST=postgres_db
      - PG_USER=admin
      - PG_DB=node_app_pg_db
    depends_on:
      - postgres_db
  postgres_db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'node_app_pg_db'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
